---
- hosts: all
  become: yes
  tasks:
    - name: Install Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install required libs
      yum:
        name:
          - "docker-ce"
          - "kubectl"

    - name: Create zuul users
      user:
        name: "zuul{{ item }}"
        groups: "docker"
      with_sequence: start=1 end=4
      register: users

    - name: Configure authorized_keys for SoftwareFactory
      authorized_key:
        user: "{{ item.name }}"
        key: "https://softwarefactory-project.io/keys/zuul_rsa.pub"
      with_items: "{{ users.results }}"

    - name: Create sudoers file
      copy:
        content: |
          %wheel  ALL=(ALL)  NOPASSWD: ALL
        dest: /etc/sudoers.d/wheel

    # This user SSHs to the nodes and performs various management / cleanup tasks
    - name: Create user for internal tower
      user:
        name: "tower"
        groups: "wheel"

    # The public part of the "GCE Zuul Nodes" key in our Tower.
    - name: Configure authorized_keys for internal Tower
      authorized_key:
        user: "tower"
        key: |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCu5KjdqyJBVFcjRFuNP5vWEkZEGRnBHLNs0M4HlJJMnrX9ZQ2LAStLSWb3w5ldAkN+A2nRBIYhMNCk6/5r4RW37b/XFQdZwbe83hSoD0zb+OBlPpYzlGa5VCUlvxkl4yKDLat4Sn2CmnB8x5N/jPxyzwVFRI1T6oDLjQhUxkS+72rIayCMDRmPXBrwXtNbW53PTJG5hQ1Os4CVH/4cy0vlqXGAyjt2fTlJIsM6FcVP5XTaXF9Eudzz7xCJErygYU1EnIwbjRJlQKkxR7C97vTwEkm8bvjxSRWdJvAjoosY69xQpfqb7lqCl4UB5Ux9ClIvu9s7yG/tkkWej8h7+7A6/IDj9KfC2L2XNAOBzRA/aVKfxcA4aeWVgipVh19L484LvgiiAwhZpvsYRCFLWszVLete2BEdIkhNVa/vVs3nF65VLumGveW1Nixs1oWj/mciyHQDm14LeqidwOpPpeUjIXxzf/1Uybvye4SyK+oMPsUQTSJd3r8CoREHMMnqjlh0ed8qYdq4l9ZE6PAkygzSTj8WAgE7fH6kzHfRkUiQJzDGcxVVaDF21tCK4gFP+PJtuysx2XeWNL/t3kVzKMzEeyfGDmTe6vWwNAn3HcUlZVOvqKqY6yXkTikbhI5fYDfj41orx9Sok/4YQn7OYjsGFs9+AmeklkehNjpZwtPlRw== jenkins@ansible.com

    - name: Start and enable docker
      service:
        name: docker
        enabled: yes
        state: started

      # https://success.docker.com/article/ipv4-forwarding
      # PR's that invoked Zuul were failing on tox command.
      # sshed to the GCE static node and ran the tox command manually.
      # On the docker build step, the below error was seen. This caused the yum
      # install to fail. The below command fixes this.
      # Step 4/40 : RUN mkdir /tmp/requirements
      #  ---> [Warning] IPv4 forwarding is disabled. Networking will not work.
      #  ---> Running in 0ff7a77d106d
      # Removing intermediate container 0ff7a77d106d
      #  ---> 725155375db4
      # Step 5/40 : RUN yum -y update && yum -y install curl epel-release && yum -y install https://centos7.iuscommunity.org/ius-release.rpm
      #  ---> [Warning] IPv4 forwarding is disabled. Networking will not work.
    - name: UCP requires IPv4 IP Forwarding
      sysctl:
        name: "net.ipv4.conf.all.forwarding"
        value: "1"
        sysctl_set: yes
        state: present
