---
- hosts: localhost
  tasks:
    - name: Validate the token
      uri:
        url: https://galaxy.ansible.com/api/_ui/v1/me/
        headers:
          Authorization: Token {{ ansible_galaxy_info.token }}
      no_log: true
      register: resp

    - name: Assert token belongs to ansibuddy
      assert:
        that: resp.json.username == "ansibuddy"
