---
- hosts: all

  tasks:

    - pip:
        name: git+https://github.com/ansible/ansible.git@devel
        extra_args: --user
        state: forcereinstall
        executable: /usr/bin/pip3

    - pip:
        name: boto
        extra_args: --user
        state: forcereinstall
        executable: /usr/bin/pip3

    - pip:
        name: boto3
        extra_args: --user
        state: forcereinstall
        executable: /usr/bin/pip3

    - lineinfile:
        dest: /tmp/secrets.yaml
        line: "{{ item }}"
        create: True
      no_log: True
      with_items:
        - "cloud_vpn_initiator_aws_access_key: {{ aws.access_key }}"
        - "cloud_vpn_initiator_aws_secret_key: {{ aws.secret_key }}"
        - "cloud_vpn_responder_aws_access_key: {{ aws.access_key }}"
        - "cloud_vpn_responder_aws_secret_key: {{ aws.secret_key }}"

    - command: "/home/zuul-worker/.local/bin/ansible-playbook test_aws_vyos_to_aws_vpn.yaml -e @/tmp/secrets.yaml"
      args:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/tests/"
