---
- hosts: all:!appliance*
  tasks:
    - name: unregister the node
      command: subscription-manager unregister
      when: ansible_distribution == "RedHat"
      become: true
      ignore_errors: yes


- hosts: all
  tasks:
    - block:
        - include_role: name=fetch-output
      when:
        - "ansible_connection != 'kubectl'"
        - ansible_user_dir is defined
    - block:
        - include_role: name=fetch-output-openshift
      when:
        - "ansible_connection == 'kubectl'"
        - ansible_user_dir is defined
    - import_role: name=merge-output-to-logs
      when: ansible_user_dir is defined

- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_sflogs }}"
    - role: generate-zuul-manifest
    - role: ara-report
      # This depends-on https://review.openstack.org/577675
      ara_report_run: True
      ara_report_type: database
      ara_report_path: "{{ zuul.executor.log_root }}/ara-report"
    - role: log-classify
      logclassify_model_store_url: https://softwarefactory-project.io/logs/classifiers
      logclassify_zuul_web: https://softwarefactory-project.io/zuul/api/tenant/local
      logclassify_model_dir: /var/lib/log-classify
      logclassify_local_dir: "{{ zuul.executor.log_root }}"

- hosts: "elk.softwarefactory-project.io"
  gather_facts: false
  tasks:
    # Use a block because play vars doesn't take precedence on roles vars
    - block:
        - import_role: name=upload-log-classify-model
        - import_role: name=upload-logs
        - import_role: name=buildset-artifacts-location
      vars:
        zuul_log_compress: true
        zuul_log_url: "https://softwarefactory-project.io/logs"
        zuul_logserver_root: "{{ site_sflogs.path }}"

- hosts: localhost
  ignore_errors: yes
  roles:
    - role: submit-logstash-jobs
      logstash_gearman_server: "elk.softwarefactory-project.io"
      logstash_gearman_server_port: 4731
