---
- hosts: localhost
  tasks:
    - block:
        - import_role: name=emit-job-header
        # This depends-on https://review.openstack.org/578234
        - import_role: name=log-inventory
      vars:
        zuul_log_url: "https://ansible.softwarefactory-project.io/logs"

- hosts: all:!appliance*
  tasks:
    - include_role: name=start-zuul-console
    - block:
        - include_role: name=validate-host
      when: "ansible_connection != 'kubectl'"


- hosts: all:!appliance
  tasks:
    - include_role: name=start-zuul-console
    - block:
        - include_role: name=prepare-workspace
        - name: Run add-build-sshkey role (RSA)
          include_role:
            name: add-build-sshkey
          vars:
            zuul_ssh_key_size: 2048
        - name: Run add-build-sshkey role (ECDSA)
          include_role:
            name: add-build-sshkey
          vars:
            zuul_ssh_key_algorithm: ecdsa
            zuul_ssh_key_size: 521
      when: "ansible_connection != 'kubectl'"
    - block:
        - include_role: name=prepare-workspace-openshift
        - include_role: name=remove-zuul-sshkey
      run_once: true
      when: "ansible_connection == 'kubectl'"
    - import_role: name=ensure-output-dirs
      when: ansible_user_dir is defined
