---
- set_fact:
    image_tag: "awx-pr-{{ zuul.change }}"
  when: image_tag is not defined

- set_fact:
    source_dir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
  when: source_dir is not defined

- set_fact:
    target_branch: "{{ zuul.branch }}"
  when: target_branch is not defined

- name: Pre-pull images
  shell: |
    docker pull gcr.io/ansible-tower-engineering/awx_devel:{{ target_branch }}
    docker pull gcr.io/ansible-tower-engineering/awx_devel:{{ image_tag }}
  ignore_errors: yes

- name: Build image
  shell: |
    docker build -f tools/docker-compose/Dockerfile \
      -t {{ image_tag }} \
      --cache-from gcr.io/ansible-tower-engineering/awx_devel:{{ image_tag }} \
      --cache-from gcr.io/ansible-tower-engineering/awx_devel:{{ target_branch }} .
  args:
    chdir: "{{ source_dir }}"

- name: Run {{ command }}
  shell: |
    docker run -u$(id -u) --rm \
      -v {{ source_dir }}:/awx_devel/:Z --workdir=/awx_devel \
      {{ image_tag }} {{ command | quote }}
